### ISSUE TITLE
Costs not calculated after upgrade to 1.8.0

### ISSUE THREAD

**Issue by aboudou** [MattJeanes/TeslaMateAgile#23]
Hello,

The charging costs are not calculated anymore since I've upgraded to 1.8.0. No changes in conf, and no TeslaMateAgile info in logs

<img width="941" alt="Capture d’écran 2021-11-09 à 08 14 36" src="https://user-images.githubusercontent.com/2165241/140878915-2816c6f8-06f4-4f7c-99e8-600ccea7fe44.png">

2021-11-07 : TeslaMateAgile 1.7.0
2021-11-08 : TeslaMateAgile 1.8.0

Conf : 

```
  teslamateagile:
    image: mattjeanes/teslamateagile:latest
    restart: always
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - TeslaMate__UpdateIntervalSeconds=300
      - TeslaMate__GeofenceId=1
      - TeslaMate__EnergyProvider=FixedPrice
      - FixedPrice__TimeZone=Europe/Paris
      - FixedPrice__Prices__0=06:30-22:30=0.1853
      - FixedPrice__Prices__1=22:30-06:30=0.1353
      - Logging__LogLevel__Default=Debug

```
Startup logs

```
teslamate_1       | 2021-11-09 07:47:01.988 [info] Migrations already up
teslamate_1       | 2021-11-09 07:47:07.647 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1       | 2021-11-09 07:47:07.647 [info] Version: 1.24.2
teslamate_1       | 2021-11-09 07:47:07.980 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (293.420 ms)
teslamate_1       | 2021-11-09 07:47:09.728 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (1746.672 ms)
teslamate_1       | 2021-11-09 07:47:09.728 [info] Refreshed api tokens
teslamate_1       | 2021-11-09 07:47:09.734 [info] Scheduling token refresh in 5 wk 5 d
teslamate_1       | 2021-11-09 07:47:09.737 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1       | 2021-11-09 07:47:09.739 [info] Access TeslaMateWeb.Endpoint at http://xxxxx.com
teslamate_1       | 2021-11-09 07:47:10.589 [info] Starting logger for 'Tut Tut Bolide'
teslamate_1       | 2021-11-09 07:47:10.603 [info] MQTT connection has been established
teslamate_1       | 2021-11-09 07:47:11.201 [info] tzdata release in place is from a file last modified Tue, 22 Dec 2020 23:35:21 GMT. Release file on server was last modified Fri, 22 Oct 2021 02:20:47 GMT.
teslamate_1       | 2021-11-09 07:47:11.422 car_id=1 [info] Start / :asleep
teslamate_1       | 2021-11-09 07:47:12.901 [info] Tzdata has updated the release from 2020e to 2021e
teslamate_1       | 2021-11-09 07:55:36.595 [info] GET /
teslamate_1       | 2021-11-09 07:55:36.610 [info] Sent 200 in 14ms

```
