### ISSUE TITLE
Feature request - Make available in Home Assitant hassio

### ISSUE THREAD

**Issue by lhomann** [MattJeanes/TeslaMateAgile#47]
Hi
Is it possible to make this available to Home Assistant hassio installations.
I have installed TeslaMate via https://github.com/matt-FFFFFF/hassio-addon-teslamate but is not able to add this TeslaMateAgile to my HA installation.

**Comment by MattJeanes** [comment]
Ooh, I like the idea of this! Especially given we have HA integration into this already it seems like a logical next step.

I'll take a look when I get a moment, but in the mean time you can run something like the Portainer addon in HA to run custom Docker containers and use it that way.

**Comment by lhomann** [comment]
Portainer is unfortunately deprecated. I do not know how to work a round that.

**Comment by MattJeanes** [comment]
Ah okay, I can only recommend running it on another machine with docker for now then if you can't do that anymore, I will look at this when I can but I am super busy so I can't guarantee that it will be soon :)

**Comment by lhomann** [comment]
Hi Matt
No hurry, I'm just happy that you like the feature request, and that it maybe someday be available.

**Comment by cho-trackman** [comment]
I'm actually running it from "inside" Home Assistant currently. I start it manually via SSH. The biggest issue is that you have to install the dotnet runtime, which is wiped on reboots. I did try to build as self-constrained, but that is for some reason not enough. I don't think I have the knowledge to drive this feature, but I would like to help and test when needed, I'm already working on a fork to support data from Monta.

**Comment by tougher** [comment]
I'm actually running it from "inside" Home Assistant currently. I start it manually via SSH. The biggest issue is that you have to install the dotnet runtime, which is wiped on reboots. I did try to build as self-constrained, but that is for some reason not enough. I don't think I have the knowledge to drive this feature, but I would like to help and test when needed, I'm already working on a fork to support data from Monta.

**Comment by MattJeanes** [comment]
Interesting, sounds like this would be useful to a few people. I haven't forgotten about this, just been a bit caught up you know how it is :)

I'll be sure to reach out if I need some testers, thank you for your offer

**Comment by tougher** [comment]
It was actually more straight forward than I initially thought, so I did take a stab at:

<img width="427" alt="image" src="https://github.com/MattJeanes/TeslaMateAgile/assets/10697/94c170ad-55e6-4442-a3ea-4008f45d1980">

It's sort of just metadata for now, next step is a `Dockerfile`, but I will use this as inspiration: https://github.com/matt-FFFFFF/hassio-addon-teslamate/blob/main/Dockerfile

**Comment by tougher** [comment]
IT'S ALIVE! But config is obviously missing :)

<img width="1248" alt="image" src="https://github.com/MattJeanes/TeslaMateAgile/assets/10697/dce0c6a4-ee26-4cb3-bd64-44109211ffa1">

I pushed my changes here: https://github.com/tougher/hassio-addon-TeslaMateAgile

**Comment by MattJeanes** [comment]
Ooh, vey nice! If you need anything from me please let me know, I'd be more than happy to link to this from the description once it's up and running, and help contribute if I make any changes in future that affect this.

**Comment by lhomann** [comment]
It is working!!! I'm using @tougher  version. I'm very happy
This is my config file:

database_user: username
database_pass: password
database_name: databasename
database_host: 29b65938-postgres
database_port: 5432
args:
  - TeslaMate__UpdateIntervalSeconds=3600
  - TeslaMate__GeofenceId=1
  - TeslaMate__EnergyProvider=Energinet
  - Energinet__Region=DK1
  - Energinet__Currency=DKK
  - Energinet__VAT=1.25
  - Energinet__FixedPrices__TimeZone=Europe/Copenhagen
  - Energinet__FixedPrices__Prices__0=00:00-06:00=0.1101
  - Energinet__FixedPrices__Prices__1=06:00-17:00=0.3303
  - Energinet__FixedPrices__Prices__2=17:00-21:00=0.9901
  - Energinet__FixedPrices__Prices__3=21:00-00:00=0.3303

**Comment by tougher** [comment]
Sounds good @lhomann! I will test it more tonight.

I will also change the maintainer of the HA add-on, currently you are @MattJeanes https://github.com/tougher/hassio-addon-TeslaMateAgile/blob/main/repository.yaml :)

Another question for you guys: should the add-on follow the same version as TeslaMateAgile? After some thinking I guess not, since it might get its own bugfixes/features.

**Comment by tougher** [comment]
I tested the `FixedPrice` and `Energinet` providers in my "prod" setup and don't see why the other providers should not work.

This is my current config taken straight from Home Assistant:

```yaml
database_user: teslamate
database_pass: ****
database_name: teslamate
database_host: 29b65938-postgres
database_port: 5432
args:
  - TeslaMate__UpdateIntervalSeconds=3600
  - TeslaMate__GeofenceId=1
  - TeslaMate__LookbackDays=7
  - Logging__Console__FormatterName=simple
  - "Logging__Console__FormatterOptions__TimestampFormat=[HH:mm:ss]\u2009"
  - TeslaMate__EnergyProvider=Energinet
  - Energinet__Region=DK2
  - Energinet__Currency=DKK
  - Energinet__VAT=1.25
  - Energinet__FixedPrices__TimeZone=Europe/Copenhagen
  - Energinet__FixedPrices__Prices__0=00:00-06:00=0.1519
  - Energinet__FixedPrices__Prices__1=06:00-17:00=0.4556
  - Energinet__FixedPrices__Prices__2=17:00-21:00=0.13668
  - Energinet__FixedPrices__Prices__3=21:00-00:00=0.4556
  - TeslaMate__FeePerKilowattHour=1.30
```

The only thing that does not fully work as expected is the custom timestamp format on the logger. The space in the end is trimmed away because of how I load the arguments from yaml to exported variables. It's really not a dealbreaker, but I guess it could be fixed. In my own config you see above I made the workaround and added `\u2009`, which is not trimmed.

I will do the last changes (and update to 1.13) tomorrow and "ship" it.

Thanks a lot @MattJeanes for making this!
