### ISSUE TITLE
Feature Request: Fixed Pricing Based on Day of Week

### ISSUE THREAD

**Issue by jakest** [MattJeanes/TeslaMateAgile#51]
My power plan is as follows:

Monday - Friday
- 00:00-08:00 low tier
- 08:00-10:00 high tier
- 10:00-15:00 low tier
- 15:00-20:00 high tier
- 20:00-00:00 low tier

Saturday - Sunday
- 00:00 - 23:59 low tier

When I charge during the weekend, the costs are calculated at a high tier rate if charging during one of the high tier times (only applicable on weekdays) as TeslaMateAgile can’t currently be setup with pricing tiers dependent upon the day of the week. 

It would be amazing to be able to set up Fixed Pricing based on the day of the week to account for that.

**Comment by MattJeanes** [comment]
Hello! Is this quite a common thing to have it vary across different days of the week? I've heard of it varying across the year before e.g. summer and winter pricing but not really across a week before.

If you have Home Assistant I'd recommend using that to set your prices as dynamically as you like, details in the readme of how to do that. If not, I could try to add something for this but I'm not sure when I'll be able to get around to it. Contributions welcome of course!

**Comment by jakest** [comment]
It does seem to be fairly common, at least in the mountain west states. The
pricing also varies across the year (summer vs winter) similar to what
you’ve mentioned, so I have a reminder to adjust the config when those
hours adjust.

The full day on the weekend is always in the lower tier pricing.

I don’t have Home Assistant currently, but maybe it’s time to check that
out.

**Comment by jfg31113** [comment]
Here in Spain we also have diferent plans for weekdays and weekends:

Monday - Friday

00:00-08:00 low tier
08:00-10:00 mid tier
10:00-14:00 high tier
14:00-18:00 mid tier
18::00-22:00 high tier
22:00-00:00 mid tier

Saturday - Sunday

00:00 - 23:59 low tier

**Comment by MattJeanes** [comment]
Hey @jakest / @jfg31113 - I have made a first version of this and I would love if you could help me test it.

I've just released test version [v1.17.0-rc.1](https://github.com/MattJeanes/TeslaMateAgile/releases/edit/v1.17.0-rc.1) which contains a new `FixedPriceWeekly` provider which should do what you want.

I have tested various different scenarios but I can't promise that it'll work perfectly, so I invite you to give it a go and try and break it, and most importantly let me know what you think!

See the [documentation](https://github.com/MattJeanes/TeslaMateAgile#fixed-price-weekly) for how to configure the new provider.

**Comment by jakest** [comment]
@MattJeanes I'm getting the following log error with the following config. 
[teslamate-teslamateagile-1.csv](https://github.com/user-attachments/files/17636574/teslamate-teslamateagile-1.csv)

```      System.ArgumentException: price (Parameter 'Failed to parse fixed price: Sat-Sun=0.052004') ```

```  teslamateagile:
    image: mattjeanes/teslamateagile:latest
    restart: always
    environment:
      - DATABASE_USER=XXXX
      - DATABASE_PASS=XXXX
      - DATABASE_NAME=XXXX
      - DATABASE_HOST=XXXX
      - TeslaMate__UpdateIntervalSeconds=3600
      - TeslaMate__GeofenceId=1
      - TeslaMate__EnergyProvider=FixedPrice
      - FixedPrice__TimeZone=America/Denver
      - FixedPrice__Prices__0=Mon-Fri=00:00-08:00=0.052004
      - FixedPrice__Prices__1=Mon-Fri=08:00-10:00=0.253532
      - FixedPrice__Prices__2=Mon-Fri=10:00-15:00=0.052004
      - FixedPrice__Prices__3=Mon-Fri=15:00-20:00=0.253532
      - FixedPrice__Prices__4=Mon-Fri=20:00-00:00=0.052004
      - FixedPrice__Prices__5=Sat,Sun=0.052004```

I've tried `Sat-Sun` as well. I've also tried `Sat-Sun=00:00-00:00=0.052004`. What should I be using for the same price the full weekend?

**Comment by MattJeanes** [comment]
Ah I see, make sure you are using the new `FixedPriceWeekly` in the `TeslaMate__EnergyProvider` setting 😄

**Comment by MattJeanes** [comment]
Oh, and all of the settings should be prefixed with `FixedPriceWeekly` instead of `FixedPrice` e.g. 

```yaml
      - TeslaMate__EnergyProvider=FixedPriceWeekly
      - FixedPriceWeekly__TimeZone=America/Denver
      - FixedPriceWeekly__Prices__0=Mon-Fri=00:00-08:00=0.052004
      - FixedPriceWeekly__Prices__1=Mon-Fri=08:00-10:00=0.253532
      - FixedPriceWeekly__Prices__2=Mon-Fri=10:00-15:00=0.052004
      - FixedPriceWeekly__Prices__3=Mon-Fri=15:00-20:00=0.253532
      - FixedPriceWeekly__Prices__4=Mon-Fri=20:00-00:00=0.052004
      - FixedPriceWeekly__Prices__5=Sat,Sun=0.052004
```

Apologies I needed to make it a brand new provider rather than extending the existing one hence the changes.

**Comment by jakest** [comment]
Ah! I didn't even notice, my mistake. Looks like I'm getting a new error now that is preventing the container from starting with this config.

```
  teslamateagile:
    image: mattjeanes/teslamateagile:latest
    restart: always
    environment:
      - DATABASE_USER=XXXX
      - DATABASE_PASS=XXXX
      - DATABASE_NAME=XXXX
      - DATABASE_HOST=XXXX
      - TeslaMate__UpdateIntervalSeconds=3600
      - TeslaMate__GeofenceId=1
      - TeslaMate__EnergyProvider=FixedPriceWeekly
      - FixedPriceWeekly__TimeZone=America/Denver
      - FixedPriceWeekly__Prices__0=00:00-08:00=0.052004
      - FixedPriceWeekly__Prices__1=08:00-10:00=0.253532
      - FixedPriceWeekly__Prices__2=10:00-15:00=0.052004
      - FixedPriceWeekly__Prices__3=15:00-20:00=0.253532
      - FixedPriceWeekly__Prices__4=20:00-00:00=0.052004
      - FixedPriceWeekly__Prices__5=Sat-Sun=0.052004
```
[teslamate-teslamateagile-1(2).csv](https://github.com/user-attachments/files/17638485/teslamate-teslamateagile-1.2.csv)
